### ISSUE TITLE
[Feat] 10조 예약 API 구현

### ISSUE THREAD

**Issue by YEJINGO** [GoldKing9/AirbnbClone_backend#16]
## 📝 todo
- [x] 숙박예약
- [x] 게스트 예약 전체 조회
- [x] 예약 취소
- [x] 예약 단건 조회
- [x] 호스트 예약 조회

**Comment by YEJINGO** [comment]
close #17 

[issue]
1. Reservation Entity에서 https://github.com/where(clause = "is_deleted = false") 삭제

호스트가 숙소 예약을 조회할 때, status가 예약중/이용완료/예약취소 로 나뉘어져 있는데, https://github.com/where(clause = "is_deleted = false")가 붙어 있으면 예약취소 상태를 표시할 수 없음
조회 시 is_deleted가 true인 값은 조회하지 않도록 쿼리에 조건문 추가
2. 예약 단건 조회 api명 수정

예약 단건 조회인데, api가 /api/auth/user/reservations/{accommodationId} 로 되어있음.
{reservationId}로 수정
3. 호스트 예약 조회

호스트 예약 조회 시, 예약에 대한 id를 추가함(reservation_id)
4. 숙박예약

숙박 예약 로직 맞는지..도와주세요!!
